### ISSUE TITLE
Mac OSX Leopard ARM toolchain binaries

### ISSUE THREAD

**Issue by bnewbold** [leaflabs/maple-ide#1]
On an OSX 10.5 Macbook, both the "arm" and "arm2" binaries throw dyln link
errors. This was the old problem which motivated the compilation of seperate
compiler binaries in the first place.

The "hidden" (__MACOSX or whatever) meta-information directories were deleted
when creating the dist zip files, that may be the cause?

Fix: recompile and test binaries for each os version and rewrite the make.sh
and dist.sh to more elegantly select the appropriate binaries. Perhaps
seperate dist archives and binary releases for each os version? Or auto
select?

**Comment by bnewbold** [comment]
http://github.com/jsnyder/arm-eabi-toolchain
This could be useful, or we could even include a script to directly fetch requirements instead of having us bundle them. I like that a lot! These 100meg dist archives suck!

**Comment by mbolivar** [comment]
fixed a million years ago, also we're not using github issues
