### ISSUE TITLE
Testing on linux distributions

### ISSUE THREAD

**Issue by bnewbold** [leaflabs/maple-ide#3]
The IDE has only been compiled and tested on Ubuntu 9.10 x86_64; at a minimum
it needs to be tested in a pure-32bit environment, and best would be testing
on, eg, Debian, Fedora, FreeBSD, and Mint.

**Comment by mbolivar** [comment]
we've tested on ubuntu 10.04 and 10.10; issues on 64 bit but easy to fix, closing since we're not using github issues
