### ISSUE TITLE
Port or replace Arduino libraries

### ISSUE THREAD

**Issue by bnewbold** [leaflabs/maple-ide#4]
We need to either integrate arduino library functions into our maple-library
or add ARM-compatible functions in #if blocks to the arduino library. Another
option is to completely replace the library files with ARM compatible ones and
either select the appropriate ones in ArmCompile.java or completely jetison
AVR compatibility.

**Comment by mbolivar** [comment]
we abandoned avr compatibility; closing because we're not using github issues
